import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

const inter = Noto_Sans({ subsets: ["cyrillic"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" h-full">
      <body className={`${inter.className}  h-full`}>
        <div className="flex flex-col h-full">
          <Header />
          <main className="pt-[48px] lg:pt-[56px] flex-[1_0_auto]">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
