import Header from "./components/Header";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

const inter = Noto_Sans({ subsets: ["cyrillic"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-[100%]`}>
        <Header />
        <main className=" pt-[56px] flex-1">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
